name: spring-hospital
services:
    mysql:
        platform: linux/arm64
        container_name: mysql-db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=prms
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        ports:
            - 3306:3306
        volumes:
            - ./mysqldata:/var/lib/mysql
            - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/
        image: mysql:8.0