CREATE TABLE IF NOT EXISTS roles (
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE -- e.g., "NURSE", "DOCTOR"
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role_id BIGINT REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS patients (
  id BIGINT PRIMARY KEY　NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  age INT NOT NULL,
  medical_history TEXT,
  hkid VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  action VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  details TEXT,
  timestamp TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  patient_id BIGINT REFERENCES patients(id),
  date_time TIMESTAMP NOT NULL,
  status VARCHAR(50) NOT NULL -- e.g., "SCHEDULED", "COMPLETED"
);

